
---
title: TRIBUTE PAGE
author: ABHIJEET RAVAT
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Tribute  pages for all great men and women. This will contain the time line of their life and the contribution they have made for the development of the world.
twitter_username: # DO NOT include the @ character, or else the build will fail!
github_username:  abhiravat # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
---
